name: backend ci

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: mongodb://localhost:27017/testdb
      GOOGLE_CLIENT_ID: dummy-client-id
      GOOGLE_CLIENT_SECRET: dummy-client-secret

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: |
          cd backend
          npm install

      - name: Run tests
        run: |
          cd backend
          npm test
